import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableRow,
  Typography,
  colors,
} from "@mui/material";
import BlockIcon from "@mui/icons-material/Block";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { useSession } from "next-auth/react";
import { Link, Loading, Title } from "react-admin";
import { api } from "~/utils/api";
import type { DateRange } from "react-day-picker";
import { addDays } from "date-fns";
import { useState } from "react";
import { DatePickerWithRange } from "../ui/dateRange";

interface StatsProps {
  dateRange: DateRange | undefined;
}

const About = () => {
  return (
    <Paper className="p-4">
      <Typography variant="h4">How to:</Typography>
      <Typography variant="h6" mt={2}>
        Navigation
      </Typography>
      <Typography variant="body1">
        <ul style={{ listStyle: "inside" }}>
          <li>
            Use the main menu (top left) to navigate through different entities.
          </li>
          <li>
            Click the profile icon (top right) to logout or go back to the main
            app.
          </li>
        </ul>
      </Typography>
      <Typography variant="h6" mt={2}>
        Entities
      </Typography>
      <Typography variant="body1">
        Each entity is made up of:
        <ul style={{ listStyle: "inside" }}>
          <li>List page - an overview of every item</li>
          <li>
            Show page - a detailed view of a single item and its relations
          </li>
          <li>Edit page - a form to edit the details of the item</li>
          <li>Create page - a form to create a new item</li>
        </ul>
      </Typography>
      <Typography variant="h6" mt={2}>
        Intended workflow
      </Typography>
      <Typography variant="body1">
        The system has been designed with the following workflow in mind,{" "}
        <strong>after</strong> a booking comes in and the initial details have
        been agreed with the client:
      </Typography>
      <Typography variant="body1" mt={1}>
        <ol
          style={{
            listStyleType: "-moz-initial",
            listStylePosition: "inside",
          }}
        >
          <li>
            Admin creates a new client and event, and assigns the event to the
            client. When the event is created a draft invoice is automatically
            generated by paypal.
          </li>
          <li>
            Admin offers the gig out to musicians by adding them to the event.
          </li>
          <li>Musicians log in and accept/decline the gig.</li>
          <li>
            Admins view the draft invoice and make any amendments as necessary
            and then click the &quot;Send invoice&quot; button.
          </li>
          <li>
            Client logs in and updates the details of their event and makes
            their payments using the paypal integration.
          </li>
        </ol>
      </Typography>
      <Typography variant="body1" mt={2}>
        Future iterations of the app will extend this workflow to include
        musicians sending/uploading their invoices through this app and
        documents being automatically generated.
      </Typography>
    </Paper>
  );
};

const StatsError = ({ title, label }: { title: string; label: string }) => (
  <Paper
    variant="outlined"
    style={{
      backgroundColor: colors.blue[50],
      padding: 10,
    }}
  >
    <Typography variant="h5">{title}</Typography>
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyItems: "center",
        gap: 10,
      }}
    >
      <BlockIcon
        color="error"
        sx={{
          fontSize: 50,
        }}
      />
      <Typography color="red">
        There was an error getting {label} from send grid.
      </Typography>
    </div>
  </Paper>
);

const EmailStats = ({ dateRange }: StatsProps) => {
  const { data, dataUpdatedAt, isLoading, isError } =
    api.stats.getSendGridStats.useQuery(dateRange);

  if (isLoading) return <Loading loadingPrimary="Getting Email stats" />;

  if (isError) {
    return <StatsError title="Email" label="email stats" />;
  }

  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h5">Email</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <br />
      <Typography variant="caption">
        These stats only apply to emails sent by the system, we use Send Grid
        for emails and that is where this data is pulled from.
      </Typography>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell>
              <Typography>Delivered</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.delivered}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Requests used</Typography>
              <Typography variant="caption">Limit is 100 per day</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.requests}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Invalid emails</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.invalid_emails}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Reported as spam</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.spam_reports}</Typography>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Paper>
  );
};

const AppStats = () => {
  const { data, isLoading, isError, dataUpdatedAt } =
    api.stats.getAppStats.useQuery();
  if (isLoading) return <Loading loadingPrimary="Getting app stats..." />;

  if (isError) return <StatsError title="Email" label="email stats" />;
  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h5">App</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <br />
      <Typography variant="caption">
        This data is not effected by the specified date range.
      </Typography>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell>
              <Typography>Users</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalUsers}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Current active users</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalSessions}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Events</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalEvents}</Typography>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Paper>
  );
};

const EventStats = ({ dateRange }: StatsProps) => {
  const { data, isLoading, isError, dataUpdatedAt } =
    api.stats.getEventStats.useQuery(dateRange);
  if (isLoading) return <Loading loadingPrimary="Getting event stats..." />;

  if (isError) return <StatsError title="Event" label="event stats" />;
  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h4">Event</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell>
              <Typography>Created</Typography>
              <Typography variant="caption">
                Number of events created within the specified time frame
              </Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalCreated}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Scheduled</Typography>
              <Typography variant="caption">
                Number of events scheduled to take place within the specified
                time frame
              </Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalBooked}</Typography>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Cancelled</Typography>
            </TableCell>
            <TableCell>
              <Typography>{data.totalCancelled}</Typography>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Paper>
  );
};

const EventTypeStats = ({ dateRange }: StatsProps) => {
  const { data, isLoading, isError, dataUpdatedAt } =
    api.stats.getEventStats.useQuery(dateRange);

  if (isLoading)
    return <Loading loadingPrimary="Getting event types stats..." />;

  if (isError) return <StatsError title="Event Types" label="event types" />;
  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h5">Event Types:</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <Table>
        <TableBody>
          {data.totalGroupedByEventType.map(({ events, name }) => (
            <TableRow key={name}>
              <TableCell>
                <Typography>{name}</Typography>
              </TableCell>
              <TableCell>
                <Typography>{events.length}</Typography>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Paper>
  );
};

const EventPackagesStats = ({ dateRange }: StatsProps) => {
  const { data, isLoading, isError, dataUpdatedAt } =
    api.stats.getEventStats.useQuery(dateRange);

  if (isLoading) return <Loading loadingPrimary="Getting packages stats..." />;

  if (isError) return <StatsError title="Packages" label="packages" />;
  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h5">Event Types:</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <Table>
        <TableBody>
          {data.totalGroupedByPackages.map(({ events, name }) => (
            <TableRow key={name}>
              <TableCell>
                <Typography>{name}</Typography>
              </TableCell>
              <TableCell>
                <Typography>{events.length}</Typography>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Paper>
  );
};

const FinanceStats = ({ dateRange }: StatsProps) => {
  const { data, isLoading, isError, dataUpdatedAt } =
    api.stats.getFinanceStats.useQuery(dateRange);

  if (isLoading) return <Loading loadingPrimary="Getting finance stats..." />;

  if (isError) return <StatsError title="Finance" label="packages" />;
  return (
    <Paper
      variant="outlined"
      style={{
        backgroundColor: colors.blue[50],
        padding: 10,
      }}
    >
      <Typography variant="h5">Finance</Typography>
      <Typography variant="caption">
        Last updated: {new Date(dataUpdatedAt).toLocaleTimeString("en-GB")}
      </Typography>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell>
              <Typography>Gross Revenue</Typography>
            </TableCell>
            <TableCell>
              {data.totalRevenue ? (
                <Typography>£{data.totalRevenue}</Typography>
              ) : (
                <Typography>No data</Typography>
              )}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Average event price</Typography>
            </TableCell>
            <TableCell>
              {data.averagePrice ? (
                <Typography>£{data.averagePrice}</Typography>
              ) : (
                <Typography>No data</Typography>
              )}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Max event price</Typography>
            </TableCell>
            <TableCell>
              {data.maxPrice ? (
                <Link to={`/event/${data.mostExpensiveEvent?.id}/show`}>
                  <Typography>£{data.maxPrice}</Typography>
                </Link>
              ) : (
                <Typography>No data</Typography>
              )}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <Typography>Min event price</Typography>
            </TableCell>
            <TableCell>
              {data.minPrice ? (
                <Link to={`/event/${data.cheapestEvent?.id}/show`}>
                  <Typography>£{data.minPrice}</Typography>
                </Link>
              ) : (
                <Typography>No data</Typography>
              )}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Paper>
  );
};

const Stats = () => {
  const [date, setDate] = useState<DateRange | undefined>({
    from: new Date(),
    to: addDays(new Date(), 1),
  });
  return (
    <Card>
      <CardContent>
        <div className="flex flex-row items-center gap-4 pb-4">
          <Typography variant="h3">Stats</Typography>
          <DatePickerWithRange date={date} setDate={setDate} />
        </div>
        <div className="gap-4 xl:flex ">
          <div className="flex flex-col gap-4 xl:w-1/3">
            <div>
              <FinanceStats dateRange={date} />
            </div>
            <div>
              <EventStats dateRange={date} />
            </div>
          </div>
          <div className="flex flex-col gap-4 xl:w-1/3">
            <div>
              <EmailStats dateRange={date} />
            </div>
            <div>
              <AppStats />
            </div>
          </div>
          <div className="flex flex-col gap-4 xl:w-1/3">
            <div>
              <EventTypeStats dateRange={date} />
            </div>
            <div>
              <EventPackagesStats dateRange={date} />
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

const Dashboard = () => {
  const session = useSession();
  const user = session?.data?.user;

  return (
    <Card sx={{ marginTop: 1 }}>
      <Title title="Admin console" />
      <CardContent className="flex gap-4">
        {/* <About /> */}
        <Stats />
      </CardContent>
    </Card>
  );
};

export default Dashboard;
